#!/bin/sh

# DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE 
# Version 2, December 2004 

# Copyright (C) 2016 Ceres Rohana <ceres.rohana@gmail.com>			

# Everyone is permitted to copy and distribute verbatim or modified 
# copies of this license document, and changing it is allowed as long 
# as the name is changed. 

# DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE 
# TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION 

# 0. You just DO WHAT THE FUCK YOU WANT TO.

MY_PK=$1
TEMP_PK="temp.snk"
UR_PK="yourpk.txt"

sn -p $MY_PK $TEMP_PK
sn -q -tp $TEMP_PK > $UR_PK

echo "I'll copy your PublicKey to the clipboard. :-)"
cat "$UR_PK" | clip
echo "Done. Just ctrl+V."

rm -f $UR_PK
rm -f $TEMP_PK
